version: '3.9'

services:
  run-file-service:
    container_name: run
    build: .
    ports:
      - 5002:5002
    volumes:
      - .:/app
      - ./volumes:/app/volumes
    environment:
      - EXECUTER=python
      - FILE_NAME=hello.py
      - PORT=5002
    command: python app.py